"""Path resolver for LAIA's Atlas registry (paths-only layer).

Reads the `paths:` block of ~/.laia/config.yaml and exposes the API that
laia-pathd, CLI tools, and scripts require.  Supports ${paths.X} interpolation
and ~ expansion.  Pure functions — no side effects except regenerate_env_file.

For the full multi-type registry (services, containers, sockets…) use atlas.py.
"""
from __future__ import annotations

import json
import logging
import os
import re
import socket as _socket
import tempfile
from pathlib import Path
from typing import Any

logger = logging.getLogger(__name__)


# ---------------------------------------------------------------------------
# Config location helpers
# ---------------------------------------------------------------------------

def _laia_config_home() -> Path:
    """Directory where laia-pathd config files live.

    Always ~/.laia/ — separate from LAIA_HOME (which is the interactive
    workspace ~/LAIA-ARCH since the 2026-05 migration).
    Override with LAIA_CONFIG_HOME for testing.
    """
    val = os.environ.get("LAIA_CONFIG_HOME", "").strip()
    return Path(val) if val else (Path.home() / ".laia")


def _default_config() -> Path:
    return _laia_config_home() / "config.yaml"


# ---------------------------------------------------------------------------
# Config loading
# ---------------------------------------------------------------------------

def load_config(config_path: Path) -> dict[str, Any]:
    """Parse a YAML config file.  Returns {} if file is missing."""
    import yaml  # type: ignore[import-untyped]
    try:
        with open(config_path) as fh:
            data = yaml.safe_load(fh)
            return data if isinstance(data, dict) else {}
    except FileNotFoundError:
        return {}
    except yaml.YAMLError as exc:
        logger.error("laia_paths: YAML error in %s: %s", config_path, exc)
        return {}


# ---------------------------------------------------------------------------
# Resolution
# ---------------------------------------------------------------------------

def resolve(cfg: dict[str, Any]) -> dict[str, str]:
    """Expand ${paths.X} and ~ in every entry of the `paths:` block.

    Returns a flat alias→absolute-path dict.
    Circular references raise ValueError; unknown references raise KeyError.
    """
    raw: dict[str, str] = {
        k: str(v) for k, v in (cfg.get("paths") or {}).items()
    }
    resolved: dict[str, str] = {}
    resolving: set[str] = set()
    home = str(Path.home())

    def _one(alias: str) -> str:
        if alias in resolved:
            return resolved[alias]
        if alias in resolving:
            raise ValueError(
                f"circular reference in paths config involving alias {alias!r}"
            )
        if alias not in raw:
            raise KeyError(f"undefined path alias: {alias!r}")

        resolving.add(alias)
        value = raw[alias].replace("~", home)

        def _sub(m: re.Match[str]) -> str:
            return _one(m.group(1))

        value = re.sub(r"\$\{paths\.([^}]+)\}", _sub, value)
        resolving.discard(alias)
        resolved[alias] = value
        return value

    for alias in raw:
        _one(alias)

    return resolved


# ---------------------------------------------------------------------------
# Env-file rendering
# ---------------------------------------------------------------------------

def render_env_file(
    paths: dict[str, str],
    *,
    source_path: Path | None = None,
) -> str:
    """Return a bash-sourceable string of `export LAIA_<KEY>="<value>"` lines."""
    lines = ["# Auto-generated by laia-pathd — do not edit manually"]
    if source_path:
        lines.append(f"# Source: {source_path}")
    lines.append("")
    for alias, path in sorted(paths.items()):
        env_key = f"LAIA_{alias.upper()}"
        lines.append(f'export {env_key}="{path}"')
    lines.append("")
    return "\n".join(lines)


def regenerate_env_file() -> Path:
    """Re-parse config.yaml and rewrite ~/.laia/.env.paths atomically."""
    home = _laia_config_home()
    config_path = home / "config.yaml"
    env_file = home / ".env.paths"

    cfg = load_config(config_path)
    paths = resolve(cfg)
    content = render_env_file(paths, source_path=config_path)

    env_file.parent.mkdir(parents=True, exist_ok=True)
    fd, tmp = tempfile.mkstemp(dir=env_file.parent, prefix=".env.paths.", suffix=".tmp")
    try:
        with os.fdopen(fd, "w") as fh:
            fh.write(content)
        os.replace(tmp, env_file)
    except Exception:
        try:
            os.unlink(tmp)
        except OSError:
            pass
        raise

    return env_file


# ---------------------------------------------------------------------------
# Daemon query (inline — no fragile cross-package import)
# ---------------------------------------------------------------------------

def _query_daemon(socket_path: Path) -> dict[str, str] | None:
    """Ask the running pathd daemon for all resolved paths.

    Returns None on any failure so callers can fall back gracefully.
    Uses raw sockets to avoid importing infra.pathd (which may not be on path).
    """
    req = (json.dumps({"id": 1, "method": "resolve_all", "params": {}}) + "\n").encode()
    try:
        s = _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM)
        s.settimeout(0.4)
        try:
            s.connect(str(socket_path))
            s.sendall(req)
            buf = b""
            while b"\n" not in buf:
                chunk = s.recv(4096)
                if not chunk:
                    break
                buf += chunk
        finally:
            s.close()
        resp = json.loads(buf.decode("utf-8", errors="replace").splitlines()[0])
        result = resp.get("result")
        if isinstance(result, dict):
            return {str(k): str(v) for k, v in result.items()}
    except Exception:
        pass
    return None


# ---------------------------------------------------------------------------
# High-level helpers
# ---------------------------------------------------------------------------

def all_paths(config_path: Path | None = None) -> dict[str, str]:
    """Return all resolved alias→path pairs.

    Tries the daemon socket first for live data; falls back to direct
    config.yaml parsing when the daemon is not running.
    """
    socket_path = _laia_config_home() / "pathd.sock"
    if socket_path.exists():
        result = _query_daemon(socket_path)
        if result is not None:
            return result

    cp = config_path or _default_config()
    return resolve(load_config(cp))


def get_path(alias: str, default: Path | None = None) -> Path:
    """Resolve a single alias to a Path.

    Resolution order:
    1. LAIA_<ALIAS> environment variable override.
    2. Running pathd daemon (if socket exists).
    3. Direct parse of config.yaml.
    4. *default* if given, else returns Path(alias) as a last resort.
    """
    env_key = f"LAIA_{alias.upper()}"
    env_val = os.environ.get(env_key, "").strip()
    if env_val:
        return Path(env_val)

    paths = all_paths()
    if alias in paths:
        return Path(paths[alias])

    return default if default is not None else Path(alias)
